/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d0c0d1",
        "on-surface": "#fcf8fb",
        "primary-fixed": "#e0e0ff",
        "tertiary": "#4bbcee",
        "surface-container-high": "#1f1e21",
        "surface-tint": "#85adff",
        "background": "#0e0e10",
        "inverse-on-surface": "#252528",
        "on-secondary-container": "#efc5ff",
        "on-primary-fixed": "#000000",
        "primary-dim": "#0070eb",
        "surface-variant": "#252528",
        "on-primary": "#002c65",
        "surface-container-lowest": "#000000",
        "error": "#ff6e84",
        "surface-container-highest": "#252528",
        "secondary-container": "#7508a5",
        "primary-container": "#6c9fff",
        "surface": "#0e0e10",
        "error-container": "#a70138",
        "secondary-fixed": "#eec2ff",
        "on-secondary-fixed-variant": "#7d19ad",
        "on-error": "#490013",
        "on-tertiary-container": "#004056",
        "on-tertiary-fixed": "#002939",
        "surface-container-low": "#131315",
        "outline": "#767577",
        "tertiary-fixed": "#5ccafc",
        "secondary": "#d277ff",
        "on-tertiary-fixed-variant": "#004962",
        "tertiary-dim": "#4bbcee",
        "on-error-container": "#ffb2b9",
        "inverse-surface": "#fcf8fb",
        "tertiary-fixed-dim": "#4bbcee",
        "secondary-fixed-dim": "#e7afff",
        "primary": "#85adff",
        "error-dim": "#d73357",
        "tertiary-container": "#5ccafc",
        "on-primary-fixed-variant": "#002a61",
        "on-secondary-fixed": "#56007c",
        "secondary-dim": "#d277ff",
        "surface-container": "#19191c",
        "inverse-primary": "#005bc2",
        "on-background": "#fefbfe"
      },
      fontFamily: {
        "sans": ["Outfit", "sans-serif"],
      }
    },
  },
  plugins: [],
}
